version: '2.4'
services:
    mongo:
        container_name: mongo_container
        image: mongo:4.4.4
        restart: unless-stopped
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin-furrax
            MONGO_INITDB_ROOT_PASSWORD: admin-furrax
            MONGO_INITDB_DATABASE: furrax
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    redis:
        container_name: redis_container
        image: redis:alpine
        command: redis-server --requirepass furrax
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
            - redis-conf:/usr/local/etc/redis/redis.conf

volumes:
  redis-data:
  redis-conf: