- hosts: app_server
  gather_facts: false
  become: true

  vars:
    server_name: "{{ groups['app_server'][0] }}"
    document_root: /var/www/html
    app_root: vue/dist

  tasks:
  - name: Install Packages
    apt:
      name: ['nginx', 'unzip']
      update_cache: yes
      state: latest
      
  - name: Create app directory
    file:
      path: "{{ document_root }}/{{ app_root }}"
      state: directory

  - name: Get artifact url
    uri:
      url: "https://api.github.com/repos/e-furrax/vue/actions/artifacts?per_page=1"
      return_content: yes
    register: github_actions

  - name: Download artifact
    get_url:
      url: "{{ (github_actions.content|from_json).artifacts[0].archive_download_url }}"
      url_username: "{{ username }}"
      url_password: "{{ access_token }}"
      force_basic_auth: yes
      dest: "{{ document_root }}/vue/dist.zip"
      mode: 0750
      
  - name: Unzip artifact
    unarchive:
      dest: "{{ document_root }}/{{ app_root }}"
      src: "{{ document_root }}/vue/dist.zip"
      remote_src: yes
      
  - name: Apply Nginx template
    template:
      src: nginx/nginx.conf.j2
      dest: /etc/nginx/sites-available/default
    notify: Restart Nginx

  - name: Enable new site
    file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link
    notify: Restart Nginx

  handlers:
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted
