name: Terraform

on:
  push:
    branches:
    - main

jobs:
  common:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout/@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Generate ssh key
        working-directory: ./ci
        run: |
          mkdir .ssh
          cd .ssh
          echo "$AWS_PRIVATE_KEY" > id_rsa_aws
          echo "$AWS_PUBLIC_KEY" > id_rsa_aws.pub
          chmod 600 *
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_PUBLIC_KEY: ${{ secrets.AWS_PUBLIC_KEY  }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: terraform init
        working-directory: ./ci/10_deploy
        run: terraform init

      - name: terraform fmt
        working-directory: ./ci/10_deploy
        run: terraform fmt

      - name: terraform plan
        working-directory: ./ci/10_deploy
        run: terraform plan -var="postgres_password=${{ secrets.POSTGRES_PASSWORD }}"

      - name: terraform apply
        working-directory: ./ci/10_deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: terraform apply --auto-approve -var="postgres_password=${{ secrets.POSTGRES_PASSWORD }}"
