name: Artifact

on:
  workflow_run:
    workflows:
      - Terraform
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: 'Artifact'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: .env
        shell: bash
        env:
          VUE_APP_BACKEND_URL: ${{ secrets.VUE_APP_BACKEND_URL }}
          VUE_APP_BACKEND_URL_WS: ${{ secrets.VUE_APP_BACKEND_URL_WS }}
        run: |
          echo "VUE_APP_BACKEND_URL=$VUE_APP_BACKEND_URL" > .env
          echo "VUE_APP_BACKEND_URL_WS=$VUE_APP_BACKEND_URL_WS" >> .env

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          retention-days: 30
