name: Ansible

on:
  workflow_run:
    workflows:
      - Artifact
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: 'Artifact'
    runs-on: ubuntu-latest

    steps:
      - name: Ansible playbook
        working-directory: ./ci/20_ansible
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'workflow_run' }}
        run: ansible-playbook install.yml --verbose --extra-vars="username=e-furrax access_token=${{ secrets.GITHUB_TOKEN }} postgres_password=${{ secrets.POSTGRES_PASSWORD }}" --private-key ../.ssh/id_rsa_aws
      
