name: Common Jobs

on: push

jobs:
  common:
    name: 'Common jobs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: .env
        shell: bash
        env:
          VUE_APP_BACKEND_URL: ${{ secrets.VUE_APP_BACKEND_URL }}
        run: |
          echo "VUE_APP_BACKEND_URL=$VUE_APP_BACKEND_URL" > .env
          echo "VUE_APP_BACKEND_URL_WS=$VUE_APP_BACKEND_URL_WS" >> .env

      - name: Run ESLint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm test

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          retention-days: 4
